backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

    media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
    public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "sam"
    label: "Sam" 
    folder: "content/about"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "hidden", default: "Podcast"}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: Author, name: author, widget: hidden, default: Chris Stayte}
      - {label: Author Image, name: authorImage, widget: hidden, default: "uploads/chrisstayte_profilepic.jpg"}
      - {label: "Header Image", name: image, widget: image, required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Sharing, name: share, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: "post"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog"
    label: "Blog" 
    folder: "content/blog"
    create: true
    slug: "/{{year}}-{{slug}}/index.md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: Author, name: author, widget: hidden, default: Chris Stayte}
      - {label: Author Image, name: authorImage, widget: hidden, default: "uploads/chrisstayte_profilepic.jpg"}
      - {label: "Header Image", name: image, widget: image, required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Sharing, name: share, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: "post"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "contact"
    label: "Contact" 
    folder: "content/contact"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: Author, name: author, widget: hidden, default: Chris Stayte}
      - {label: Author Image, name: authorImage, widget: hidden, default: "uploads/chrisstayte_profilepic.jpg"}
      - {label: "Header Image", name: image, widget: image, required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Sharing, name: share, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: "post"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "post"
    label: "Post" 
    folder: "content/post"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: "string", required: true}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: Author, name: author, widget: hidden, default: Chris Stayte}
      - {label: Author Image, name: authorImage, widget: hidden, default: "uploads/chrisstayte_profilepic.jpg"}
      - {label: "Header Image", name: image, widget: image, required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Sharing, name: share, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: "post"}
      - {label: "Body", name: "body", widget: "markdown"}    
  - name: "search"
    label: "Search" 
    folder: "content/search"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Categories", name: "categories", widget: hidden, default: coding}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: Author, name: author, widget: hidden, default: Chris Stayte}
      - {label: Author Image, name: authorImage, widget: hidden, default: "uploads/chrisstayte_profilepic.jpg"}
      - {label: "Header Image", name: image, widget: image, required: false}
      - {label: Commenting, name: comments, widget: boolean, default: true}
      - {label: Sharing, name: share, widget: boolean, default: true}
      - {label: Type, name: type, widget: hidden, default: "post"}
      - {label: "Body", name: "body", widget: "markdown"}